### ISSUE TITLE
Unable to find template "SonataUserBundle:Form:form_admin_fields.html.twig"

### ISSUE THREAD

**Issue by darienmh** [Runroom/SonataUserBundle#4]
I'm trying to couple Runroom / SonataUserBundle in my project with Symfony 3.4 and PHP 5.6, but it turns out that they do not load the templates.

### Unable to find template "SonataUserBundle:Form:form_admin_fields.html.twig" (looked into: /var/www/html/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /var/www/html/app/Resources/views, /var/www/html/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).

Could you guide me about this?

**Comment by roberto910907** [comment]
Since you're using Symfony **3.4** you should use `@SonataUser/Form/form_admin_fields.html.twig`.

> If you need to refer to a template that lives in a bundle, Symfony uses the Twig namespaced syntax (@BundleName/directory/filename.html.twig).

**Comment by darienmh** [comment]
thank you very much, it worked!
